# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := har_to_pagespeed
DEFS_Debug := '-DGOOGLE_PROTOBUF_NO_RTTI' \
	'-DPAGESPEED_PNG_OPTIMIZER_GIF_READER' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug :=

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -Ithird_party/chromium/src \
	-I. \
	-Ithird_party/instaweb/src \
	-Ithird_party/protobuf2 \
	-Ithird_party/protobuf2/src/src \
	-I$(obj)/gen/protoc_out

DEFS_Release := '-DGOOGLE_PROTOBUF_NO_RTTI' \
	'-DPAGESPEED_PNG_OPTIMIZER_GIF_READER' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-fno-asynchronous-unwind-tables

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release :=

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -Ithird_party/chromium/src \
	-I. \
	-Ithird_party/instaweb/src \
	-Ithird_party/protobuf2 \
	-Ithird_party/protobuf2/src/src \
	-I$(obj)/gen/protoc_out

OBJS := $(obj).target/$(TARGET)/pagespeed/samples/har_to_pagespeed.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/base/libbase.a $(obj).target/pagespeed/core/libpagespeed_init.a $(obj).target/pagespeed/formatters/libpagespeed_formatters.a $(obj).target/pagespeed/har/libpagespeed_har.a $(obj).target/pagespeed/image_compression/libpagespeed_image_attributes_factory.a $(obj).target/pagespeed/libpagespeed_library.a $(obj).target/build/temp_gyp/libgoogleurl.a $(obj).target/third_party/instaweb/src/net/instaweb/libinstaweb_htmlparse_core.a $(obj).target/third_party/instaweb/src/net/instaweb/libinstaweb_util_core.a $(obj).target/third_party/protobuf2/libprotobuf_lite.a $(obj).target/pagespeed/core/libpagespeed_core.a $(obj).target/pagespeed/proto/libpagespeed_output_pb.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/third_party/cJSON/libcJSON.a $(obj).target/pagespeed/image_compression/libpagespeed_jpeg_reader.a $(obj).target/third_party/libjpeg/libjpeg.a $(obj).target/pagespeed/image_compression/libpagespeed_png_optimizer.a $(obj).target/third_party/libpng/libpng.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/third_party/optipng/libopngreduc.a $(obj).target/third_party/optipng/libpngxrgif.a $(obj).target/net/libnet_base.a $(obj).target/third_party/jsmin/libjsmin.a $(obj).target/pagespeed/cssmin/libpagespeed_cssmin.a $(obj).target/pagespeed/html/libpagespeed_html.a $(obj).target/third_party/instaweb/src/net/instaweb/libinstaweb_rewriter_html.a $(obj).target/pagespeed/image_compression/libpagespeed_jpeg_optimizer.a $(obj).target/third_party/libjpeg_trans/libjpeg_trans.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack \
	-rdynamic

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,--gc-sections

LIBS := -lrt \
	-lm

$(builddir)/har_to_pagespeed: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/har_to_pagespeed: LIBS := $(LIBS)
$(builddir)/har_to_pagespeed: TOOLSET := $(TOOLSET)
$(builddir)/har_to_pagespeed: $(OBJS) $(obj).target/base/libbase.a $(obj).target/pagespeed/core/libpagespeed_init.a $(obj).target/pagespeed/formatters/libpagespeed_formatters.a $(obj).target/pagespeed/har/libpagespeed_har.a $(obj).target/pagespeed/image_compression/libpagespeed_image_attributes_factory.a $(obj).target/pagespeed/libpagespeed_library.a $(obj).target/build/temp_gyp/libgoogleurl.a $(obj).target/third_party/instaweb/src/net/instaweb/libinstaweb_htmlparse_core.a $(obj).target/third_party/instaweb/src/net/instaweb/libinstaweb_util_core.a $(obj).target/third_party/protobuf2/libprotobuf_lite.a $(obj).target/pagespeed/core/libpagespeed_core.a $(obj).target/pagespeed/proto/libpagespeed_output_pb.a $(obj).target/third_party/modp_b64/libmodp_b64.a $(obj).target/third_party/cJSON/libcJSON.a $(obj).target/pagespeed/image_compression/libpagespeed_jpeg_reader.a $(obj).target/third_party/libjpeg/libjpeg.a $(obj).target/pagespeed/image_compression/libpagespeed_png_optimizer.a $(obj).target/third_party/libpng/libpng.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/third_party/optipng/libopngreduc.a $(obj).target/third_party/optipng/libpngxrgif.a $(obj).target/net/libnet_base.a $(obj).target/third_party/jsmin/libjsmin.a $(obj).target/pagespeed/cssmin/libpagespeed_cssmin.a $(obj).target/pagespeed/html/libpagespeed_html.a $(obj).target/third_party/instaweb/src/net/instaweb/libinstaweb_rewriter_html.a $(obj).target/pagespeed/image_compression/libpagespeed_jpeg_optimizer.a $(obj).target/third_party/libjpeg_trans/libjpeg_trans.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/har_to_pagespeed
# Add target alias
.PHONY: har_to_pagespeed
har_to_pagespeed: $(builddir)/har_to_pagespeed

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/har_to_pagespeed

