# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := optimize_image_bin
DEFS_Debug := '-DPAGESPEED_PNG_OPTIMIZER_GIF_READER' \
	'-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug :=

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -Ithird_party/chromium/src \
	-I.

DEFS_Release := '-DPAGESPEED_PNG_OPTIMIZER_GIF_READER' \
	'-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-fno-asynchronous-unwind-tables

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release :=

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -Ithird_party/chromium/src \
	-I.

OBJS := $(obj).target/$(TARGET)/pagespeed/samples/optimize_image.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/pagespeed/image_compression/libpagespeed_jpeg_optimizer.a $(obj).target/pagespeed/image_compression/libpagespeed_png_optimizer.a $(obj).target/pagespeed/image_compression/libpagespeed_jpeg_reader.a $(obj).target/base/libbase.a $(obj).target/third_party/libjpeg/libjpeg.a $(obj).target/third_party/libjpeg_trans/libjpeg_trans.a $(obj).target/third_party/libpng/libpng.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/third_party/optipng/libopngreduc.a $(obj).target/third_party/optipng/libpngxrgif.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack \
	-rdynamic

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,--gc-sections

LIBS := -lrt

$(builddir)/optimize_image_bin: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/optimize_image_bin: LIBS := $(LIBS)
$(builddir)/optimize_image_bin: TOOLSET := $(TOOLSET)
$(builddir)/optimize_image_bin: $(OBJS) $(obj).target/pagespeed/image_compression/libpagespeed_jpeg_optimizer.a $(obj).target/pagespeed/image_compression/libpagespeed_png_optimizer.a $(obj).target/pagespeed/image_compression/libpagespeed_jpeg_reader.a $(obj).target/base/libbase.a $(obj).target/third_party/libjpeg/libjpeg.a $(obj).target/third_party/libjpeg_trans/libjpeg_trans.a $(obj).target/third_party/libpng/libpng.a $(obj).target/third_party/zlib/libchrome_zlib.a $(obj).target/third_party/optipng/libopngreduc.a $(obj).target/third_party/optipng/libpngxrgif.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/optimize_image_bin
# Add target alias
.PHONY: optimize_image_bin
optimize_image_bin: $(builddir)/optimize_image_bin

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/optimize_image_bin

