# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := base
DEFS_Debug := '-D__STDC_FORMAT_MACROS' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-D_DEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Debug := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-Wno-write-strings \
	-Wno-error \
	-Wno-write-strings \
	-O0 \
	-g

# Flags passed to only C (and not C++) files.
CFLAGS_C_Debug := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Debug := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := -Ithird_party/chromium/src

DEFS_Release := '-D__STDC_FORMAT_MACROS' \
	'-DNDEBUG'

# Flags passed to both C and C++ files.
CFLAGS_Release := -Werror \
	-pthread \
	-fno-exceptions \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-Wno-write-strings \
	-Wno-error \
	-Wno-write-strings \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-fno-asynchronous-unwind-tables

# Flags passed to only C (and not C++) files.
CFLAGS_C_Release := 

# Flags passed to only C++ (and not C) files.
CFLAGS_CC_Release := -fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := -Ithird_party/chromium/src

OBJS := $(obj).target/$(TARGET)/third_party/chromium/src/base/third_party/dynamic_annotations/dynamic_annotations.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/third_party/dmg_fp/dtoa.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/third_party/dmg_fp/g_fmt.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/third_party/nspr/prtime.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/atomicops_internals_x86_gcc.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/at_exit.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/debug_util.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/debug_util_posix.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/lock.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/lock_impl_posix.o \
	$(obj).target/$(TARGET)/base/logging.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/platform_thread_posix.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/safe_strerror_posix.o \
	$(obj).target/$(TARGET)/base/stats_table.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/string_number_conversions.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/string_piece.o \
	$(obj).target/$(TARGET)/base/string_util.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/string16.o \
	$(obj).target/$(TARGET)/base/stub_utf.o \
	$(obj).target/$(TARGET)/third_party/chromium/src/base/md5.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE)) $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := -pthread \
	-Wl,-z,noexecstack \
	-rdynamic

LDFLAGS_Release := -pthread \
	-Wl,-z,noexecstack \
	-Wl,--gc-sections

LIBS := 

$(obj).target/base/libbase.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/base/libbase.a: LIBS := $(LIBS)
$(obj).target/base/libbase.a: TOOLSET := $(TOOLSET)
$(obj).target/base/libbase.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/base/libbase.a
# Add target alias
.PHONY: base
base: $(obj).target/base/libbase.a

# Add target alias to "all" target.
.PHONY: all
all: base

